### ISSUE TITLE
Display of "open and closed issues" taking a long time

### ISSUE THREAD

**Issue by Sing-Li** [shubhsherl/GSoC-Contribution-Leaderboard#29] opened 2019-03-10 15:36 UTC
From @kareemhamdy100
```
close and open issues will take a very long time we have big huge data in the org - I think we should discuss about this problem
```

If this is the case, IMO - we *should* update this on a less frequent basis - once EVERY DAY or EVERY TWO DAYS should be fine.   The importance of the metrics, on this leaderboard, for GSoC tracking purposes are - in order:

1)  PRs accepted
2) PRs pending  BUT cleared all CI/CLA errors - ready to merge
3) Open and closed issue

----

1) because it indicates and shows that the Student has made a significant contribution recognized by the core team member(s) who merged it

2) because it does take significant effort to make a PR - even if not accepted; and it takes significantly more effort to keep it updated while pending (that's why ready-to-merge is important criteria)

3) least important, although still shows willingness to contribute  [and somewhat subject to abuse]

Other ideas / opinions?

**Comment by shubhsherl** [comment] 2019-03-10 16:39
@Sing-Li @kareemhamdy100 
For now, the REQUIRED DATA is  (Open and Merged)PRs and (Open and Closed) Issues.
* With the approach of fetching issues/PRs by repo it takes, around 15-20min(irrespective of the number of users registered, since we are fetching all PRs and issues).
* With search, as mentioned earlier time spend, is around 10users/min(since API calls depend on the number of users registered).
Both have some pros and cons.

**Comment by Sing-Li** [comment] 2019-03-10 17:05
@shubhsherl  That's actually a good point.  

It is a good time to consider, NOT to over-simplify the problem (simplifying was a good way to bootstrap start a project) and look into the details.

The REQUIRED DATA is more fine grained -- see my post.  

Also, the solution does **NOT** have to be Black and White - either "Pull by Repo" **OR** "Pull by Search" 

It might be a mixture of (Repo + Search) x  (one-shot-manual-trigger +  looped)

Keep in mind that - anything we conclude here is NOT for the current release, but a future improvement release of the project.

**Comment by shubhsherl** [comment] 2019-03-10 20:09
@Sing-Li Yes, the mixture of both can be a good strategy, fetching all PR(whose number is much less than issues) + fetch all the issues per user.
> Why this improves performance?
> Since Github issue with `state=all` contains all issues as well as PRs (because every PR is an issue but not the other way around).
> PR(with `state=all`) gives both Merge + Open PRs, and async we can fetch issues per user(by search, 30 users per minute).

For `PRs pending BUT cleared all CI/CLA errors - ready to merge` :
I guess, even a PR with some CI/CLA errors should be eligible for Open PR.

**Comment by kareemhamdy100** [comment] 2019-03-14 14:28
I think we should remove   issues from leaderboard it express no thing  about code or competition

**Comment by shubhsherl** [comment] 2019-03-19 16:35
The problem is solved in the first release. If you find any other discrepancy please open it again.

**Closed as completed by shubhsherl** 2019-03-19 16:35 UTC
Labels: discussion
